package Multiset;

/**
 * An interface for objects capable of generating Sequences.
 * @author Kevin Cosgrove
 */

public interface Sequenced {
    /**@return The sequence generated by the Sequenced object.*/
    public Sequence seq();
}
